openapi: 3.2.0
info:
  description: Cybersec API documentation
  version: 1.0.0
  title: Cybersec Cookies API
servers:
- url: https://cybersec.nordstellar.com
security:
- ApiKeyAuth: []
tags:
- name: Cookies
paths:
  /v3/cybersec/cookies/check:
    post:
      operationId: cookiesCheck
      tags:
      - Cookies
      summary: Perform a leaked cookies check
      description: This endpoint performs leaked cookies check on supported by Serity service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CookiesCheckRequest'
            example:
              short_cookie_sha256:
              - '12345678'
              - '12233441'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CookiesCheckResponse'
              example:
                cookies:
                - hash: 7cbd4cb8d64ca4f37e697cf77d580feaf3823d62860b3fd3429108332feea153
                  domain: some-site.com
                - hash: 7dbd4cb8d64ca4f37e697cf77d580feaf3823d62860b3fd3429108332feea153
                  domain: another-site.com
          headers:
            X-Correlation-ID:
              $ref: '#/components/schemas/X-Correlation-ID'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Authorization header not provided:
                  $ref: '#/paths/~1v2~1cybersec~1lists/get/responses/400/content/application~1json/examples/Authorization%20header%20not%20provided'
                Invalid authorization header:
                  $ref: '#/paths/~1v2~1cybersec~1lists/get/responses/400/content/application~1json/examples/Invalid%20authorization%20header'
                Invalid cookie format:
                  value:
                    errors:
                      code: 904183
                      message: Invalid cookie format
          headers:
            X-Correlation-ID:
              $ref: '#/components/schemas/X-Correlation-ID'
        '401':
          $ref: '#/components/responses/InvalidCredentials'
        '403':
          $ref: '#/components/responses/ServiceForbidden'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/ResourcesExhausted'
        '503':
          $ref: '#/components/responses/AuthServiceUnavailable'
components:
  schemas:
    CookiesCheckResponse:
      type: object
      properties:
        cookies:
          type: array
          items:
            type: object
            properties:
              hash:
                type: string
                example: 7fdd4cb8d64ca4f37e697cf77d580feaf3823d62860b3fd3429108332feea153
                description: This hash is composed by a hashed combination of domain + cookie-hash
              domain:
                type: string
                example: the-leaked-domain-here.com
    X-RateLimit-Retry-After:
      type: string
      format: rfc3999
      example: '2024-03-25T15:19:06.000Z'
      description: Time when requests to the resource aren't limited.
    X-Correlation-ID:
      type: string
      format: uuid
      example: ddd58a90-57c3-4bd1-a9ed-649a9451f0a7
      description: Unique identifier for correlating requests, responses and logs across distributed services
    CookiesCheckRequest:
      type: object
      properties:
        short_cookie_sha256:
          type: array
          items:
            type: string
            example: '12345678'
          description: List of cookie hashes (8 char) to be checked
    ErrorResponse:
      type: object
      properties:
        errors:
          type: object
          properties:
            code:
              type: integer
              example: 123
            message:
              type: string
              example: Some error
  responses:
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Content too large:
              value:
                errors:
                  code: 904175
                  message: Exceeded the limit of 20 records to check in a batch
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
    ResourcesExhausted:
      description: Service resources exhausted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Too many requests:
              value:
                errors:
                  code: 904174
                  message: Too many requests, try again later
      headers:
        X-RateLimit-Retry-After:
          $ref: '#/components/schemas/X-RateLimit-Retry-After'
    AuthServiceUnavailable:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Service unavailable:
              value:
                errors:
                  code: 904178
                  message: Service temporary unavailable
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
    InvalidCredentials:
      description: Invalid credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Invalid credentials:
              value:
                errors:
                  code: 100104
                  message: Invalid credentials
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
    ServiceForbidden:
      description: Service is forbidden for the user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Service is forbidden for the user:
              value:
                errors:
                  code: 100166
                  message: Service is forbidden for the user
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Set token with a prefix like this: `token:69405a802dba4f57804e5fff11061946a579d159d1a51760d19a50aec241adc9`'
