openapi: 3.2.0
info:
  description: Cybersec API documentation
  version: 1.0.0
  title: Cybersec Crypto Addresses API
servers:
- url: https://cybersec.nordstellar.com
security:
- ApiKeyAuth: []
tags:
- name: Crypto Addresses
paths:
  /v3/cybersec/cryptoaddresses/check:
    post:
      operationId: cryptoAddressesCheck
      tags:
      - Crypto Addresses
      summary: Perform a crypto addresses check
      description: This endpoint performs a crypto addresses check.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CryptoAddressesCheckRequest'
            example:
              url: http://example.com/abc
              addresses:
              - '0xABC12345abc123'
              - '0xCDE67890cde456'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  reputations:
                  - address: '0xABC12345abc123'
                    category: 1
                    chains:
                    - chain_id: chain_12
                      risks:
                      - risk_category: 1
                        score: 12
                  - address: '0xCDE67890cde456'
                    category: 1
                    chains:
                    - chain_id: chain_12
                      risks:
                      - risk_category: 1
                        score: 12
          headers:
            X-Correlation-ID:
              $ref: '#/components/schemas/X-Correlation-ID'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Authorization header not provided:
                  $ref: '#/paths/~1v2~1cybersec~1lists/get/responses/400/content/application~1json/examples/Authorization%20header%20not%20provided'
                Invalid authorization header:
                  $ref: '#/paths/~1v2~1cybersec~1lists/get/responses/400/content/application~1json/examples/Invalid%20authorization%20header'
                Invalid url:
                  $ref: '#/paths/~1v2~1cybersec~1urls~1check/post/responses/400/content/application~1json/examples/Invalid%20url'
                Invalid address:
                  value:
                    errors:
                      code: 904185
                      message: Invalid crypto address
                Invalid address request:
                  value:
                    errors:
                      code: 904186
                      message: Invalid crypto address request
          headers:
            X-Correlation-ID:
              $ref: '#/components/schemas/X-Correlation-ID'
        '401':
          $ref: '#/components/responses/InvalidCredentials'
        '403':
          $ref: '#/components/responses/ServiceForbidden'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/ResourcesExhausted'
        '503':
          $ref: '#/components/responses/AuthServiceUnavailable'
components:
  responses:
    AuthServiceUnavailable:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Service unavailable:
              value:
                errors:
                  code: 904178
                  message: Service temporary unavailable
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Content too large:
              value:
                errors:
                  code: 904175
                  message: Exceeded the limit of 20 records to check in a batch
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
    ServiceForbidden:
      description: Service is forbidden for the user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Service is forbidden for the user:
              value:
                errors:
                  code: 100166
                  message: Service is forbidden for the user
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
    InvalidCredentials:
      description: Invalid credentials
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Invalid credentials:
              value:
                errors:
                  code: 100104
                  message: Invalid credentials
      headers:
        X-Correlation-ID:
          $ref: '#/components/schemas/X-Correlation-ID'
    ResourcesExhausted:
      description: Service resources exhausted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Too many requests:
              value:
                errors:
                  code: 904174
                  message: Too many requests, try again later
      headers:
        X-RateLimit-Retry-After:
          $ref: '#/components/schemas/X-RateLimit-Retry-After'
  schemas:
    X-RateLimit-Retry-After:
      type: string
      format: rfc3999
      example: '2024-03-25T15:19:06.000Z'
      description: Time when requests to the resource aren't limited.
    CryptoAddressesCheckRequest:
      type: object
      properties:
        url:
          type: string
          example: https://example.com/abc
        addresses:
          type: array
          items:
            type: string
            example: 0x43fbzxc24jg234f34
          description: List of crypto addresses to be checked
    X-Correlation-ID:
      type: string
      format: uuid
      example: ddd58a90-57c3-4bd1-a9ed-649a9451f0a7
      description: Unique identifier for correlating requests, responses and logs across distributed services
    ErrorResponse:
      type: object
      properties:
        errors:
          type: object
          properties:
            code:
              type: integer
              example: 123
            message:
              type: string
              example: Some error
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Set token with a prefix like this: `token:69405a802dba4f57804e5fff11061946a579d159d1a51760d19a50aec241adc9`'
